#!/bin/bash
#
# chkconfig: 2345 55 25
# description: fvq service.
default_fvq_home=/home/ec2-user/FVQ
fvq_home=$default_fvq_home
logs=$fvq_home/logs
mkdir -p $logs

########################################
# get pid of fvq service is started
########################################
function search_pid() {
  pid=`ps aux | grep fvq-polling.sh | grep -v grep | awk '{print $2}'`
  return $pid
}

########################################
# start fvq service
########################################
function start_service() {
  pid=`search_pid`
  if [ ! -z $pid ]; then
    echo "fvq service is running."
    return
  fi
  echo "Start fvq service..."
  nohup $fvq_home/sh/fvq-polling.sh >/dev/null 2>&1 &
}

########################################
# stop fvq service
########################################
function stop_service() {
  echo "Wait for fvq service stop..."
  pid=`search_pid`
  if [ ! -z $pid ]; then
    kill $pid
  fi
}

########################################
# restart fvq service
########################################
function restart_service() {
  stop_service
  start_service
}


# main process
########################################
case "$1" in
  start)
    start_service
    ;;
  restart)
    restart_service
    ;;
  stop)
    stop_service
    ;;
  *)
    echo $"Usage: fvq {start|stop}"
esac
